#!/Library/Frameworks/Python.framework/Versions/3.10/bin/python3

import sys
from PIL import Image

if len(sys.argv) != 3:
  print(f"Usage: {sys.argv[0]} <input_image> <output_image>")
  sys.exit(1)

input_path = sys.argv[1]
output_path = sys.argv[2]

with Image.open(input_path) as img:
  new_width = 1080
  scale = new_width / img.width
  new_height = int(img.height * scale)

  resized = img.resize((new_width, new_height), Image.Resampling.LANCZOS)
  resized.save(output_path)
